print("welcome!")
print("welcome!")
print("welcome!")
print("To my Practice session")
print("To my Practice session")
print("To my Practice session")
print("HHHHHHH")
print("Nooooooo")
print("Yessssss")
