print("Conflict")
print("Conflict")
print("Conflict")
print("Rises")
print("Rises")
print("Rises")
print("Same file with different data on two branches")
print("Same file with different data on two branches")
print("Same file with different data on two branches")
print("Rises")
print("Rises")
print("Rises")
print("or occurs")
print("or occurs")
print("or occurs")
print("or occurs")
print("Same file with different data on two branches")
print("Same file with different data on two branches")
print("Same file with different data on two branches")
print("Thanks youuuuu")
print("Thanks youuuuu")
print("Thanks youuuuu")


