print("Conflict")
print("Conflict")
print("Conflict")
print("afdsghgjnb")
print("Rises")
print("Rises")
print("Rises")
print("or occurs")
print("or occurs")
print("or occurs")
print("or occurs")
print("Same file with different data on two branches")
print("Same file with different data on two branches")
print("Same file with different data on two branches")
print("aaantebdbfhfh")